name: Build and Upload .deb to Release

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dpkg-deb
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev

      - name: Build amd64 .deb
        run: ./packaging/build-deb.sh ${{ github.ref_name }} amd64

      - name: Build arm64 .deb
        run: ./packaging/build-deb.sh ${{ github.ref_name }} arm64

      - name: Upload .deb files to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            arcanadbbackup_${{ github.ref_name }}_amd64.deb
            arcanadbbackup_${{ github.ref_name }}_arm64.deb
